"""Repository contract for analysis state and durable jobs."""

from typing import Any, Protocol

from backend.models import Job, Track


class AnalysisRepository(Protocol):
    def mark_track_analyzing(self, track_id: str) -> None: ...
    def update_track_analysis(self, track: Track) -> Track: ...
    def create_job(self, project_id: str, kind: str, payload: dict[str, Any], total: int = 0) -> Job: ...
    def update_job(self, job_id: str, **changes: Any) -> Job | None: ...
    def get_job(self, job_id: str) -> Job | None: ...
    def recover_jobs(self) -> list[Job]: ...
