"""Repository contract for track metadata and project membership."""

from typing import Protocol

from backend.models import Track, TrackUpdate


class TracksRepository(Protocol):
    def get_track(self, track_id: str) -> Track | None: ...
    def all_tracks(self, project_id: str | None = None) -> list[Track]: ...
    def tracks_by_ids(self, track_ids: list[str], project_id: str | None = None) -> list[Track]: ...
    def source_tracks(self, source_id: str) -> list[Track]: ...
    def upsert_track(self, track: Track, file_hash: str, project_id: str,
                     source_id: str | None = None) -> Track: ...
    def update_track(self, track_id: str, update: TrackUpdate) -> Track | None: ...
    def remove_track_from_project(self, project_id: str, track_id: str) -> bool: ...
